[package]
name = "python-config"
version = "0.1.0"
authors = ["David Hewitt <1939362+davidhewitt@users.noreply.github.com>"]
edition = "2018"
description = "Utility crate to get Python interpreter configuration."
license = "MIT"

[dependencies]
